# Generated by Django 4.2.7 on 2024-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='memo-bubble/profile_images/default_profile_qdfffx', upload_to='memo-bubble/profile_images'),
        ),
    ]
