# Generated by Django 3.2.4 on 2024-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
