# Generated by Django 3.2.4 on 2024-04-19 08:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20240419_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
