# Generated by Django 3.2.4 on 2024-05-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactform_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
