# Generated by Django 4.2.7 on 2024-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_remove_geminimessage_capsule_geminimessage_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_taken'], 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_taken'], 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
