# Generated by Django 4.2.7 on 2024-06-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_alter_image_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geminimessage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='geminimessage',
            name='videos',
        ),
        migrations.AddField(
            model_name='geminimessage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gemini_messages', to='capsules.image'),
        ),
        migrations.AddField(
            model_name='geminimessage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gemini_messages', to='capsules.video'),
        ),
    ]
