# Generated by Django 4.2.7 on 2024-06-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_remove_geminimessage_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
