# Generated by Django 4.2.7 on 2024-07-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_rename_image_images_rename_video_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='url',
        ),
    ]
