# Generated by Django 4.2.7 on 2024-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0006_rename_image_images_url_rename_video_videos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.URLField(),
        ),
    ]
