# Generated by Django 4.2.7 on 2024-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0007_alter_videos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(),
        ),
    ]
