# Generated by Django 4.2.7 on 2024-07-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0008_alter_images_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
